spring:
  application:
    name: pronnect-api
  datasource:
    url: jdbc:postgresql://localhost:5432/pronnect
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  sql:
    init:
      mode: never

jwt:
  secret: u7Q9jK8vTzFh2XzYwq3n5pL8sV0hR2mJ4d9aB6cE7fI=
  expiration: 86400000